create table if not exists public.nse_large_deals (
  id text primary key,
  deal_date date,
  exchange text not null default 'NSE',
  symbol text not null,
  company_name text,
  client_name text,
  action text,
  quantity numeric,
  price numeric,
  value_cr numeric,
  deal_type text,
  remarks text,
  source_url text,
  raw_payload jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nse_large_deals_action_check
    check (action is null or action in ('BUY', 'SELL')),
  constraint nse_large_deals_deal_type_check
    check (deal_type is null or deal_type in ('bulk', 'block', 'short', 'large')),
  constraint nse_large_deals_symbol_not_blank
    check (length(trim(symbol)) > 0)
);

comment on table public.nse_large_deals is
  'NSE Large Deals data fetched from https://www.nseindia.com/market-data/large-deals and related NSE historical large-deal endpoints.';

comment on column public.nse_large_deals.id is
  'Deterministic SHA-256 hash generated by the app from deal_date, symbol, client_name, action, quantity, price, and deal_type. Used for idempotent upserts.';

comment on column public.nse_large_deals.value_cr is
  'Deal value in Indian crore rupees when supplied by NSE or derived upstream.';

comment on column public.nse_large_deals.raw_payload is
  'Original NSE record payload retained for audit/debugging because NSE response fields can change over time.';

create index if not exists nse_large_deals_deal_date_idx
  on public.nse_large_deals (deal_date desc);

create index if not exists nse_large_deals_symbol_date_idx
  on public.nse_large_deals (symbol, deal_date desc);

create index if not exists nse_large_deals_client_date_idx
  on public.nse_large_deals (client_name, deal_date desc);

create index if not exists nse_large_deals_buy_date_idx
  on public.nse_large_deals (deal_date desc)
  where action = 'BUY';

create index if not exists nse_large_deals_sell_date_idx
  on public.nse_large_deals (deal_date desc)
  where action = 'SELL';

create index if not exists nse_large_deals_type_date_idx
  on public.nse_large_deals (deal_type, deal_date desc);

create or replace function public.set_nse_large_deals_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_nse_large_deals_updated_at on public.nse_large_deals;

create trigger set_nse_large_deals_updated_at
before update on public.nse_large_deals
for each row
execute function public.set_nse_large_deals_updated_at();
